services:
  - type: web
    name: accounting
    env: python
    buildCommand: "./render-build.sh"
    startCommand: gunicorn accounting.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: False 