"""
Django settings for accounting project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from urllib.parse import urlparse

import json
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file in development
if not os.getenv('FLY_APP_NAME'):
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

def _get_env_list(name, default=None):
    raw_value = os.getenv(name)
    if not raw_value:
        return default or []

    raw = raw_value.strip()

    # If the env var is a JSON list like ["a", "b"], parse it.
    if raw.startswith('[') and raw.endswith(']'):
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, list):
                return [str(item).strip().strip("\"'") for item in parsed if str(item).strip()]
        except Exception:
            # fall back to comma-splitting
            pass

    # Otherwise split on commas and strip surrounding quotes and whitespace
    items = []
    for item in raw.split(','):
        s = item.strip().strip("\"'")
        if s:
            items.append(s)
    return items


def _add_host_from_env(env_name, add_csrf=True):
    raw_value = os.getenv(env_name)
    if not raw_value:
        return
    # sanitize surrounding whitespace and quotes
    raw = raw_value.strip().strip("\"'")
    parsed = urlparse(raw) if '://' in raw else None
    host = (parsed.hostname if parsed else raw).split('/')[0].split(':')[0]
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)
    if add_csrf and host:
        csrf_origin = f"https://{host}"
        if csrf_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(csrf_origin)


def _ensure_in_list(values, item):
    if item and item not in values:
        values.append(item)


# Statically allow the production Railway domain and its subdomains.
# This is a fail-safe to bypass environment var parsing issues in Railway UI.
ALLOWED_HOSTS = [
    'Ableaccounting.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
    '.pythonanywhere.com',
    'ableinfra-accounts-production.up.railway.app',
    'ableinfra-production.up.railway.app',
    '.up.railway.app',
    '.railway.app',
]

# Allow additional hosts from environment variables if present.
ALLOWED_HOSTS.extend(_get_env_list('ALLOWED_HOSTS'))
# Deduplicate
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

CSRF_TRUSTED_ORIGINS = _get_env_list(
    'CSRF_TRUSTED_ORIGINS',
    default=[
        'https://Ableaccounting.pythonanywhere.com',
        'https://*.pythonanywhere.com',
        'https://*.up.railway.app',
        'https://*.railway.app',
    ],
)

# Render sets this automatically; add it when present
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# Railway may expose a public domain or URL
_add_host_from_env('RAILWAY_PUBLIC_DOMAIN')
_add_host_from_env('RAILWAY_PUBLIC_URL')

# Railway deployments frequently use `*.up.railway.app` for the public URL.
# If we detect we are running on Railway but the explicit host vars were not
# provided, allow Railway subdomains so the app can start.
IS_RAILWAY = any(
    os.getenv(name)
    for name in (
        'RAILWAY_ENVIRONMENT',
        'RAILWAY_PROJECT_ID',
        'RAILWAY_SERVICE_ID',
        'RAILWAY_PUBLIC_DOMAIN',
        'RAILWAY_PUBLIC_URL',
    )
)

if IS_RAILWAY:
    _ensure_in_list(ALLOWED_HOSTS, 'ableinfra-accounts-production.up.railway.app')
    _ensure_in_list(ALLOWED_HOSTS, 'ableinfra-production.up.railway.app')
    _ensure_in_list(ALLOWED_HOSTS, '.up.railway.app')
    _ensure_in_list(ALLOWED_HOSTS, '.railway.app')
    _ensure_in_list(CSRF_TRUSTED_ORIGINS, 'https://ableinfra-accounts-production.up.railway.app')
    _ensure_in_list(CSRF_TRUSTED_ORIGINS, 'https://ableinfra-production.up.railway.app')
    _ensure_in_list(CSRF_TRUSTED_ORIGINS, 'https://*.up.railway.app')
    _ensure_in_list(CSRF_TRUSTED_ORIGINS, 'https://*.railway.app')

# Honor proxy headers on platforms like Railway
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# During local development, ensure common local hosts are always allowed.
# This guarantees `127.0.0.1:8000` and `localhost` requests won't be blocked
# when `DEBUG=True` even if the environment variable parsing fails.
if DEBUG:
    _ensure_in_list(ALLOWED_HOSTS, '127.0.0.1')
    _ensure_in_list(ALLOWED_HOSTS, 'localhost')
    _ensure_in_list(ALLOWED_HOSTS, '::1')

# Ensure Railway domains are always allowed (covers cases where env vars
# override defaults on the platform). This makes `web-production-*.up.railway.app`
# and similar subdomains accepted by Django's host header checks.
_ensure_in_list(ALLOWED_HOSTS, '.up.railway.app')
_ensure_in_list(ALLOWED_HOSTS, '.railway.app')
_ensure_in_list(CSRF_TRUSTED_ORIGINS, 'https://*.up.railway.app')
_ensure_in_list(CSRF_TRUSTED_ORIGINS, 'https://*.railway.app')

# Ensure Railway hosts are explicitly allowed, even if env parsing has issues.
for _host in ('ableinfra-accounts-production.up.railway.app', 'ableinfra-production.up.railway.app'):
    if _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

# Debug: log ALLOWED_HOSTS at startup (temporary - remove after debugging)
import sys
print("ALLOWED_HOSTS (startup):", ALLOWED_HOSTS, file=sys.stderr)
print("CSRF_TRUSTED_ORIGINS (startup):", CSRF_TRUSTED_ORIGINS, file=sys.stderr)
print("DATABASE_URL (startup):", os.getenv('DATABASE_URL'), file=sys.stderr)
print("DATABASE_PUBLIC_URL (startup):", os.getenv('DATABASE_PUBLIC_URL'), file=sys.stderr)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clients',
    'transactions',
    'bank',
    'home',
    'accounts',
    'django_extensions',
    'acclive',







]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'login'

# Redirect users after successful login
LOGIN_REDIRECT_URL = 'dashboard'

# Redirect users after logout
LOGOUT_REDIRECT_URL = 'login'
LOGOUT_URL = 'logout'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'accounting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accounting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = (
    os.getenv('DATABASE_PUBLIC_URL')
    or os.getenv('DATABASE_URL')
    or os.getenv('DATABASE_PRIVATE_URL')
)

# If Railway provides both internal and public URLs, prefer the public one when
# the selected URL points at the internal DNS name.
if DATABASE_URL and 'railway.internal' in DATABASE_URL and os.getenv('DATABASE_PUBLIC_URL'):
    DATABASE_URL = os.getenv('DATABASE_PUBLIC_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            # Require SSL for managed Postgres providers in production
            ssl_require=not DEBUG,
        )
    }
else:
    # Local development fallback
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Configure SSL and other Postgres options
db_config = DATABASES['default']
if db_config.get('ENGINE') == 'django.db.backends.postgresql':
    db_config['OPTIONS'] = {
        'sslmode': 'require',
        'connect_timeout': 10,
    }

# Add these settings for better performance
CONN_MAX_AGE = 600
CONN_HEALTH_CHECKS = True

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT= BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Security settings for production
if not DEBUG and not (
    '127.0.0.1' in ALLOWED_HOSTS or 'localhost' in ALLOWED_HOSTS
):
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
