# Generated by Django 5.1.7 on 2025-03-26 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('site_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank', models.BooleanField(default=False)),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('transaction_type', models.CharField(blank=True, choices=[('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Deposit', 'Deposit')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount_balance', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
