# Generated by Django 5.1.7 on 2025-04-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acclive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableentry',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
