# Generated by Django 5.1.7 on 2025-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('amount_given', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
