# Generated by Django 5.1.7 on 2025-03-23 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('site_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
